### ISSUE TITLE
upolad to ESP8266

### ISSUE THREAD

**Issue by ingeea** [ekstrand/ESP8266wifi#17]
Hello community,

in the section describing this library, the author said that this library is tested with ESP8266 module with Firmware 0.9.2.4

does that mean that the Programm compiled by arduino IDE 1.6.0 could be uploaded to the Module directy? I mean i don't Need to upload it to an atmega328p or other arduino board?

If so i can not upload it directly to the module! have you did that before? 

thnx.

**Comment by ekstrand** [comment]
This code is intended to run on an arduino and speak with the esp's default firmware.
/Jonas
