### ISSUE TITLE
esp8266 - mysql

### ISSUE THREAD

**Issue by darcicidade** [ekstrand/ESP8266wifi#24]
hello, is it possible to connect esp8266 with mysql?

**Comment by cederberg** [comment]
What do you mean?

This is a library for simple message passing over WiFi. The MySQL wire protocol is quite complicated, so not easily accomplished. Better to build a server that responds to simple commands (and writes to MySQL as you wish).

**Comment by darcicidade** [comment]
sorry for the incomplete question!
My problem is when you have LOST WIFI.
The database is not synchronized. 
I will check the mysql.h library.
thank you so much.
  good week
