### ISSUE TITLE
AT_firmware for ESP_01

### ISSUE THREAD

**Issue by PA0MHE** [ekstrand/ESP8266wifi#31]
Dear Jonas,

Thanks for this very impressive library.

I see you tested with Firmware 0.9.2.4 does this also fit in an ESP_01 ? and where can I obtain this firmware.
I tried flashing AT_firmware V1.3.0.2 for ESP_12 but I'm affraid it is too large.

Thank Maarten

**Comment by ekstrand** [comment]
Hi!
I have not tested in any other esp platform or  at firmware version. But I would like to know what configurations that work :)

Regards
Jonas Ekstrand

**Comment by PA0MHE** [comment]
Dear Jonas,

Thanks for the very quick response.
Sure I hope to validate your work on my platform(s).

Do you know from where to download Firmware 0.9.2.4 ?

Thanks Maarten

**Comment by PA0MHE** [comment]
Found a firmware quite close https://github.com/espressif/ESP8266_AT
