### ISSUE TITLE
Missing method for local IP

### ISSUE THREAD

**Issue by rpseng** [ekstrand/ESP8266wifi#7]
Dear ekstrand,

First of all, nice work with this library!

Other libraries have a function called ESP8266Wifi.localIP which returns the local IP. Is there a similar function in your library?

All the best.

**Comment by ekstrand** [comment]
I have not needed one yet. If you would like to write one I would be glad to put it in! Have a lot on my plate right now soo it could otherwise be a while until I get the time to write it myself.
/Jonas

**Comment by rpseng** [comment]
Hi Jonas, thanks for the prompt reply. I don't actually need it either, just something nice to check if the module is working properly.

I'm not familiar with compiling an Arduino module. If I succeed I'll let you know.

All the best.

**Comment by ekstrand** [comment]
Ok, you could use the isconnectedtoap function for exactly that. It checks that the module has aquired a valid ip and not 0.0.0.0
:) Jonas
