### ISSUE TITLE
Question: HTTP wrappers

### ISSUE THREAD

**Issue by romangromov** [ekstrand/ESP8266wifi#8]
Hi @ekstrand, thanks for your great library.

Is there any known wrappers to support `HTTP` stuff over `ESP8266wifi` library? I mean it would be great to use such a functions like below

```
HttpRequest req = new HttpRequest();
req.setUrl("hello/world");
req.setHeader("Accpet-Encodings", "gzip")
wifi.send(SERVER, req);
```

instead of low-level `Strings` manipulation to build http request message manually.

Thank you in advance!

**Comment by ekstrand** [comment]
Hi,
I don't know. If some one wrote one I would be happy to include it in the library. I personally don't use http :)

Hälsningar/Regards
Jonas Ekstrand 
+46736397439

Inspirativ AB | www.inspirativ.se | Smyckegränd 18 12641 Hägersten

**Comment by romangromov** [comment]
@ekstrand thank you for response, anyway

**Comment by ekstrand** [comment]
You are welcome. If wish I hade the time to add that feature, it would be
nice for all of you doing http.
/ Jonas

2015-06-24 22:08 GMT+02:00 Roman Gromov notifications@github.com:

> @ekstrand https://github.com/ekstrand thank you for response, anyway
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ekstrand/ESP8266wifi/issues/8#issuecomment-114995558.

## 

Mvh/Regards
Jonas Ekstrand
0736-397439

Inspirativ AB | Org. nr. 556763-5494 | jonas@inspirativ.se |
www.inspirativ.se
